@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Organization Employee" as ADM
participant ":DishTypeRestController" as UI
participant ":CreateorUpdateDishTypeController" as CTRL
participant "DishTypeRepository" as RepositorySingleton
participant "DishType" as Class
participant "DishTypeMapper" as Mapper

activate ADM

        ADM -> UI : asks to create or update a "DishType"

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL


            UI -> CTRL : CreateOrUpdateDishRectangle()
            activate CTRL

                CTRL -> RepositorySingleton : findByAcronym()
                activate RepositorySingleton

                    RepositorySingleton --> Class
                deactivate RepositorySingleton
            deactivate CTRL
            alt SucessfullCase
            activate Class
             Class -> Mapper : update(acronym, dto)
             activate Mapper
             Mapper -> Class : setDesignation(dto.designation)
             Class -> Mapper : i.toDTO();
             deactivate Class
             deactivate Mapper
             Mapper <- UI :i.toDTO;

             alt NotSucessfulCase
             activate Class
             Class -> Mapper : Create(acronym, dto)
             activate Mapper
             Mapper -> Class : setDesignation(dto.designation)
             Class -> Mapper : i.toDTO();
             deactivate Class
             deactivate Mapper
              Mapper <- UI :i.toDTO;

    deactivate UI

deactivate ADM

@enduml